baseURL = 'https://streamshub.io'
languageCode = 'en-us'
title = 'StreamsHub'

[module]
  replacements = "github.com/FortAwesome/Font-Awesome -> ., github.com/twbs/bootstrap -> ."
[[module.imports]]
  path = "docsy"

[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

[markup]
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = true

[menu]
  [[menu.main]]
    name = 'Documentation'
    pageRef = '/docs'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 2
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 3
